/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponentExplorer: typeof import('./src/components/ComponentExplorer.vue')['default']
    ComponentField: typeof import('./src/components/ComponentField.vue')['default']
    ComponentItem: typeof import('./src/components/ComponentItem.vue')['default']
    ComponentList: typeof import('./src/components/ComponentList.vue')['default']
    ComponentProp: typeof import('./src/components/ComponentProp.vue')['default']
    ComponentProps: typeof import('./src/components/ComponentProps.vue')['default']
    ComponentSlot: typeof import('./src/components/ComponentSlot.vue')['default']
    ComponentView: typeof import('./src/components/ComponentView.vue')['default']
    copy: typeof import('./src/components/ComponentView copy.vue')['default']
    EditorLayout: typeof import('./src/components/EditorLayout.vue')['default']
    FileExplorer: typeof import('./src/components/FileExplorer.vue')['default']
    FileExplorerItem: typeof import('./src/components/FileExplorerItem.vue')['default']
    LeftSidebar: typeof import('./src/components/LeftSidebar.vue')['default']
    PrototypeView: typeof import('./src/components/PrototypeView.vue')['default']
    RightSidebar: typeof import('./src/components/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaField: typeof import('./src/components/SchemaField.vue')['default']
    UApp: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDrawer: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue')['default']
    UForm: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputNumber: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    ULinkBase: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    USelectMenu: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USwitch: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
