/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponentExplorer: typeof import('./src/components/ComponentExplorer.vue')['default']
    ComponentView: typeof import('./src/components/ComponentView.vue')['default']
    EditorLayout: typeof import('./src/components/EditorLayout.vue')['default']
    FileExplorer: typeof import('./src/components/FileExplorer.vue')['default']
    FileExplorerItem: typeof import('./src/components/FileExplorerItem.vue')['default']
    LeftSidebar: typeof import('./src/components/LeftSidebar.vue')['default']
    RightSidebar: typeof import('./src/components/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    ULinkBase: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
  }
}
